language: python
python:
  - 2.6
  - 2.7
install:
  - pip install Pillow
  - pip install coverage
  - python setup.py develop
script:  coverage run -m landez.tests
after_success:
  - pip install coveralls
  - coveralls
